name: Simple Nix Cache Action
description: Imports/exports the nix store to/from the actions cache
author: Trev
branding:
  icon: chevron-up
  color: yellow

inputs:
  key:
    description: An explicit key for the cache entry.
    required: false

outputs:
  cache-hit:
    description: A string value to indicate an exact match was found for the key.
    value: ${{ steps.nix-cache.outputs.cache-hit }}

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup.js
