name: Nix Simple Cache Action
description: Imports/exports the nix store to/from the actions cache
author: Trev
branding:
  icon: chevron-up
  color: yellow

inputs:
  max-size:
    description: Maximum size of the cache in bytes.
    default: 1000000000 # 1GB
    required: false

outputs:
  cache-hit:
    description: A string value to indicate if the cache was found.
    value: ${{ steps.nix-cache.outputs.cache-hit }}

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup.js
